"""Anonymous session token issue/verify (FIX 8).

verify_anon_token must accept only tokens this service minted (kind="anon",
valid signature, unexpired, with a sid) and reject everything else — crucially
login-style JWTs (which carry userId and no kind), so the anon-quota token and
the auth token can never be confused.
"""
from __future__ import annotations

import time

from jose import jwt

from backend.config import get_settings
from backend.services.anon_token import (
    ANON_TOKEN_TTL_DAYS,
    issue_anon_token,
    verify_anon_token,
)


def _secret() -> str:
    return get_settings().jwt_secret


def test_issue_verify_round_trip():
    tok = issue_anon_token("sess-abc")
    assert verify_anon_token(tok) == "sess-abc"


def test_autogenerated_sid_is_unique():
    sid1 = verify_anon_token(issue_anon_token())
    sid2 = verify_anon_token(issue_anon_token())
    assert sid1 and sid2
    assert sid1 != sid2  # fresh uuid4 each time


def test_login_style_token_rejected():
    # Auth tokens carry userId and NO kind — must not verify as an anon token.
    login = jwt.encode({"userId": "u1"}, _secret(), algorithm="HS256")
    assert verify_anon_token(login) is None


def test_wrong_kind_rejected():
    tok = jwt.encode({"sid": "s", "kind": "user"}, _secret(), algorithm="HS256")
    assert verify_anon_token(tok) is None


def test_missing_sid_rejected():
    tok = jwt.encode({"kind": "anon"}, _secret(), algorithm="HS256")
    assert verify_anon_token(tok) is None


def test_expired_rejected():
    tok = jwt.encode(
        {"sid": "s", "kind": "anon", "exp": int(time.time()) - 5},
        _secret(),
        algorithm="HS256",
    )
    assert verify_anon_token(tok) is None


def test_bad_signature_rejected():
    assert verify_anon_token(issue_anon_token("s") + "tamper") is None


def test_foreign_secret_rejected():
    tok = jwt.encode(
        {"sid": "s", "kind": "anon", "exp": int(time.time()) + 3600},
        "a-different-secret",
        algorithm="HS256",
    )
    assert verify_anon_token(tok) is None


def test_empty_and_none_rejected():
    assert verify_anon_token("") is None
    assert verify_anon_token(None) is None


def test_ttl_is_ninety_days():
    assert ANON_TOKEN_TTL_DAYS == 90
    decoded = jwt.decode(issue_anon_token("s"), _secret(), algorithms=["HS256"])
    span = decoded["exp"] - decoded["iat"]
    assert 89 * 86400 <= span <= 91 * 86400
